Make root/pool arguments optional
Server is retrieved from the pacman configuration through repofind.

See #158

diff --git a/bin/aurbuild b/bin/aurbuild
--- a/bin/aurbuild
+++ b/bin/aurbuild
@@ -93,45 +93,31 @@ if (($#)); then
     fi
 fi
 
-if [[ $root && ! $pool ]]; then
-    pool=$root
-fi
-
-for arg in queue database pool root; do
-    if [[ -z ${!arg} ]]; then
-        error "$argv0: $arg: missing argument"
-        err++
-    fi
-done
-
-if ((err)); then
+if [[ -z ${!database} ]]; then
+    error "$argv0: database: missing argument"
     usage; exit 1
-fi
-
-# Canonicalize paths to avoid relative path issues (#130)
-pool=$(realpath -e -- "$pool")
-root=$(realpath -e -- "$root")
-
-if [[ ! -r $queue ]]; then
-    error "$argv0: queue file $queue could not be read"
-    exit 13
-elif [[ -d $queue ]]; then
-    error "$argv0: queue file $queue is a directory"
-    exit 21
-elif [[ ! -w $root ]]; then
-    error "$argv0: repository root $root is not writeable"
-    exit 13
-elif [[ ! -w $pool ]]; then
-    error "$argv0: repository pool $pool is not writeable"
-    exit 13
-elif [[ ! -d $root ]]; then
-    error "$argv0: repository root $root is not a directory"
-    exit 20
-elif [[ ! -d $pool ]]; then
-    error "$argv0: repository pool $pool is not a directory"
-    exit 20
 elif ! pacconf --repo="$database" >/dev/null; then
     exit 22
+fi
+
+if [[ -z ${!queue} ]]; then
+    error "$argv0: queue: missing argument"
+    usage; exit 1
+elif [[ ! -r $queue || -d $queue ]]; then
+    error "$argv0: queue: must be a readable file"
+    exit 13
+fi
+
+if [[ $root ]]; then
+    root=$(realpath -e -- "$root")
+else
+    root=$(repofind -p "$database")
+fi
+
+if [[ $pool ]]; then
+    pool=$(realpath -e -- "$pool")
+else
+    pool=$root
 fi
 
 if ((chroot)); then
