aurbuid: allow build if PWD contains PKGBUILD

diff --git a/bin/aurbuild b/bin/aurbuild
--- a/bin/aurbuild
+++ b/bin/aurbuild
@@ -96,8 +96,13 @@ if [[ $queue ]]; then
         exit 13
     fi
 else
-    error "$argv0: queue: missing argument"
-    usage; exit 1
+    if [[ -r ./PKGBUILD ]]; then
+        # http://pubs.opengroup.org/onlinepubs/000095399/basedefs/xbd_chap04.html#tag_04_11
+        exec 3<<< '//'
+    else
+        error "$argv0: queue: missing argument"
+        usage; exit 1
+    fi
 fi
 
 if [[ $root ]]; then
@@ -158,8 +163,8 @@ while read -r -u 3 pkg _; do
         pkglist+=($(find "$pool" -type f -regex ".+/$p.pkg.+?"))
     done
 
-    # https://bugs.archlinux.org/task/49946
     if ((sign_pkg)); then
+        # https://bugs.archlinux.org/task/49946
         for p in "${pkglist[@]}"; do gpg "${gpg_args[@]}" "$p"; done
     fi
 
