aurgrep: reorganize
Stuff I haven't figured out yet:

- awk strftime / printf(...)T: does not seem to take the AUR date string
which contains "Jun"
- sed oneliner '1p;d' does not print the first line and saves only the
second line in the output file

diff --git a/bin/aurgrep b/bin/aurgrep
--- a/bin/aurgrep
+++ b/bin/aurgrep
@@ -7,63 +7,51 @@ set -o pipefail
 
 # https://lists.archlinux.org/pipermail/aur-dev/2016-May/004036.html
 declare -i delay=300
-declare list=packages.gz
+declare    list=packages
 
 curl_date() {
-    curl -fsSI "$1" | awk -F', ' '/^Date:/ {print $2}'
+    curl -fsSI "$1" | awk -F', ' '/^date:/ {print $2}'
 }
 
-curl_unzip_with_date() {
-    declare -r uri=$1 out=$2
-
-    curl -fsS "$uri" -o - | gzip -d - > "$out" || return
-
-    sed -n '1p' "$out" > timestamp
-    sed -i '1d' "$out"
+curl_unzip() {
+    curl -fsS "$1" -o - | gzip -d -
 }
 
-sync_list() {
-    declare -r uri=$1 file_r=${1##*/}
-    declare -r plain=${file_r%.*}
-
-    if [[ -s $plain && -s timestamp ]]; then
-        declare -i epoch_l epoch_r
-
-        read -r epoch_l < <(date -d "$(awk -F', ' '{print $3}' timestamp)" '+%s')
-        read -r epoch_r < <(date -d "$(curl_date "$uri")" '+%s')
-
-        if ((epoch_l)) && ((epoch_r)) && ((epoch_r - epoch_l > delay)); then
-            curl_unzip_with_date "$uri" "$plain"
-        fi
-    else
-        curl_unzip_with_date "$uri" "$plain"
-    fi
+extract_head() {
+    sed -n '1p' "$1"
+    sed -i '1d' "$1"
 }
 
-readonly -f curl_date curl_unzip_with_date sync_list
-
-source /usr/share/makepkg/util.sh || exit
-
-if [[ -t 2 ]] && [[ ! -o xtrace ]]; then
-    colorize
-fi
+readonly -f curl_date curl_unzip extract_head
 
 while getopts :bt OPT; do
     case "$OPT" in
-        b) list=pkgbase.gz ;;
+        b) list=pkgbase  ;;
         t) delay=$OPTARG ;;
     esac
 done
 shift $((OPTIND - 1))
 OPTIND=1
 
-mkdir -p     "$cache"
+mkdir -p "$cache"
 chmod -c 700 "$cache"
-cd_safe      "$cache"
+cd "$cache" || exit
 
-# Takes an URI to a compressed package list
-sync_list "$aurweb/$list" || exit
+readonly uri=$aurweb/$list.gz
 
-pcregrep "$@" "${list%.*}"
+if [[ -s $list && -s timestamp ]]; then
+    read -r epoch_l < <(date -d "$(awk -F', ' '{print $3}' timestamp)" '+%s')
+    read -r epoch_r < <(date -d "$(curl_date "$uri")" '+%s')
+
+    if ((epoch_l)) && ((epoch_r)) && ((epoch_r - epoch_l > delay)); then
+        curl_unzip "$uri" > "$list" || exit # keep curl exit code
+        extract_head "$list" > timestamp
+    fi
+else
+    curl_unzip "$uri" > "$list" || exit
+    extract_head "$list" > timestamp
+fi
+
+pcregrep "$@" "$list"
 
 # vim: set et sw=4 sts=4 ft=sh:
