revert to EINVAL
Technically we pass a file as an argument to tsort, and this file is
faulty.

diff --git a/bin/aurqueue b/bin/aurqueue
--- a/bin/aurqueue
+++ b/bin/aurqueue
@@ -34,8 +34,8 @@ isvalid() {
     if datamash -W check < "$1" >/dev/null; then
         tsort "$1" | tac > "$2"
     else
-        error "$argv0: bad message"
-        exit 74
+        error "$argv0: invalid argument"
+        exit 22
     fi
 }
 
