Improve error reporting
It just works: http://i.imgur.com/cG9Te.jpg

diff --git a/bin/aursearch b/bin/aursearch
--- a/bin/aursearch
+++ b/bin/aursearch
@@ -15,10 +15,9 @@ stamp() {
     declare stamp_l stamp_r fetch
     
     if stamp_l=$(stat --format '%Y' "${gz%.*}" 2>/dev/null); then
-        # aurweb lacks a "Last-Modified" field, so use head to close the
-        # pipe after reading one line.
-        # XXX: curl returns 141, noticed by pipefail
-        stamp_r=$(curl -sS "$1" | gzip -cd 2>/dev/null | head -1 | awk -F, '{print $3}')
+        # XXX: aurweb lacks a "Last-Modified" field. Instead, use head
+        # to close the pipe after reading one line (exit code 141).
+        stamp_r=$(curl -s "$1" | gzip -cd 2>/dev/null | head -1 | awk -F, '{print $3}')
 
         if [[ $stamp_r ]]; then
             stamp_r=$(date -d "$stamp_r" '+%s')
@@ -40,6 +39,7 @@ stamp() {
 # The actual "match" is done by aurweb; as such, string=1 is similar
 # to grep --fixed-strings.
 match() {
+    #global string
     if ((string)); then
         printf '%s\n' "${@:2}"
     else
@@ -57,20 +57,30 @@ split() {
         gsub("@","%40")
 
         if (NR == 1 || (NR % 150) == 0)
-            printf "\n%s&arg[]=%s", rpc, $0;
+            printf "\n%s&arg[]=%s", rpc, $0
         else
-            printf "&arg[]=%s", $0;
+            printf "&arg[]=%s", $0
     }'
 }
 
 getjson() {
+    # aria2c either dumps all errors on stdout, or doesn't display
+    # them at all. Preserve exit status, and mention the log file.
+    aria2c -d "$tmp" -l "$cache"/aria2c.log --log-level=error -q -i - || ret=$?
+
+    if ((ret)); then
+        error "$argv0: see $cache/aria2c.log"
+        exit "$ret"
+    fi
+
     # If stdin is empty, aria reports "No files to download" (even
     # with -q) and returns 0.
-    aria2c -s 16 -x 16 -j 32 -d "$tmp" -i - >/dev/null
-
     if [[ -s "$tmp"/index.html ]]; then
         # Merge to a single JSON structure.
         awk '{print}' "$tmp"/index.html* | sed -e '1i[' -e '$!s/$/,/' -e '$a]'
+    else
+        error "$argv0: no data available"
+        exit 61
     fi
 }
 
