aursrcver: simplify error handling
Only the makepkg log of the first failed package is relevant; print it
to stdout.

diff --git a/bin/aursrcver b/bin/aursrcver
--- a/bin/aursrcver
+++ b/bin/aursrcver
@@ -21,21 +21,10 @@ find_pkgbuild_path() {
     find "$@" -maxdepth 1 -type f -name PKGBUILD -printf '%h\n'
 }
 
-trap_err() {
-    printf '%s: error: see %s\n' "$argv0" "$1"
-    exit 1
-}
-
-trap_exit() {
-    # preserve makepkg log on error
-    ((!$?)) && rm "$1"
-}
-
-readonly -f get_pkgbuild_info find_pkgbuild_path trap_err trap_exit
+readonly -f get_pkgbuild_info find_pkgbuild_path
 
 makepkg_log=$(mktemp -t makepkg.XXXXXXXX) || exit
-trap 'trap_err  $makepkg_log' ERR
-trap 'trap_exit $makepkg_log' EXIT
+trap 'rm $makepkg_log' EXIT
 
 # trickery for hyphen and absolute path arguments
 mapfile -t arg_path < <(readlink -e -- "$@")
@@ -43,8 +32,13 @@ mapfile -t arg_path < <(readlink -e -- "$@")
 find_pkgbuild_path "${arg_path[@]}" | while read -r; do
     cd "$REPLY"
 
-    makepkg --noprepare -od >>"$makepkg_log" 2>&1
-    get_pkgbuild_info "$REPLY"
+    if makepkg --noprepare -od >"$makepkg_log" 2>&1; then
+        get_pkgbuild_info "$REPLY"
+    else
+        printf >&2 '%s: error on package %s\n' "$argv0" "$REPLY"
+        printf >&2 '8<----\n'
+        cat "$makepkg_log"; exit 1
+    fi
 done
 
 # vim: set et sw=4 sts=4 ft=sh:
