aursync: make aursift -S optional

diff --git a/bin/aursync b/bin/aursync
--- a/bin/aursync
+++ b/bin/aursync
@@ -12,7 +12,7 @@ AURDEST=${AURDEST:-$XDG_CACHE_HOME/$argv0}
 readonly PS4 argv0 aurweb tmp XDG_CACHE_HOME AURDEST
 
 declare -i view=1 build=1 chkver=1 deps=1 fetch=1
-declare -i update=0 snapshot=0 sign=0 rotate=0 chroot=0
+declare -i update=0 snapshot=0 sign=0 rotate=0 chroot=0 sift=0
 declare -i bindro=0 force=0 keep=0 logdest=0 namcap=0 chtemp=0
 
 # stdin: /path/to/repo.git
@@ -73,15 +73,6 @@ download() {
     done
 }
 
-i686() {
-    awk -v arch="$(uname -m)" '{
-        if(arch == "i686") {
-            gsub(/^lib32-/,"")
-            gsub(/^gcc-multilib$/,"")
-        };  print
-    }'
-}
-
 viewer() {
     if hash 2>/dev/null vifm; then
         vifm - '+view!'
@@ -117,9 +108,7 @@ repo_select() {
 
     while read -r repo server; do
         avail[$repo]=$server
-    done < <(
-        repo_list | awk -F'\t' '$2 ~ /^file:\/\//'
-    )
+    done < <(repo_list | awk -F'\t' '$2 ~ /^file:\/\//')
 
     if [[ ${avail[@]} ]]; then
 	if [[ ${#avail[@]} -gt 1 ]]; then
@@ -181,9 +170,9 @@ if getopt -T || (($? != 4)); then
     exit 22
 fi
 
-longopts=allan,allsrc,chroot,force,keep,log,help,nobuild,nodeps,nofetch,nover,noview,sign,tar,temp,update,repo:
+longopts=allan,allsrc,chroot,force,keep,log,help,nobuild,nodeps,nofetch,nover,noview,sign,sift,tar,temp,update,repo:
 
-if TEMP=$(getopt -o B:cfhkLnstTu -l "$longopts" -n "$argv0" -- "$@"); then
+if TEMP=$(getopt -o B:cfhkLnsStTu -l "$longopts" -n "$argv0" -- "$@"); then
     eval set -- "$TEMP"
 else
     usage
@@ -199,6 +188,7 @@ while true; do
         -L|--log)    logdest=1;  shift ;;
         -n)          namcap=1;   shift ;;
         -s|--sign)   sign=1;     shift ;;
+        -S|--sift)   sift=1;     shift ;;
         -T|--temp)   chtemp=1;   shift ;;
         -u|--update) update=1;   shift ;;
         -t|--tar)    snapshot=1; shift ;;
@@ -275,7 +265,7 @@ if ((update)); then
     list=($(pacman -Slq "$repo"))
     set -- "$@" "${list[@]}"
 
-    if ((!$#)); then
+    if ! (($#)); then
         plain "there is nothing to do"
         exit 0
     fi
@@ -289,30 +279,33 @@ mkdir {tsv,json,diff}
 
 if ((deps)); then
     msg "Resolving dependencies..."
-    q=($(aurchain -a -- "$@"))
+    queue=($(aurchain -a -- "$@"))
 else
-    q=("$@")
+    queue=("$@")
 fi
-
-aursearch -Fr -- "${q[@]}" > json/results
+    
+aursearch -Fr -- "${queue[@]}" > json/results
 
 jq -r '.[].results[].Name' json/results > tsv/pkgname
 jq -r '.[].results[] | [.Name,.PackageBase] | @tsv' json/results > tsv/pkgbase
 jq -r '.[].results[] | [.Name,.Version] | @tsv' json/results > tsv/pkgver
 jq -r '.[].results[] | [.PackageBase,.URLPath] | @tsv' json/results > tsv/urlpath
 
-# Print unavailable packages (#139)
-print "${q[@]}" | tee queue_0 | aursift -S | cat - <(print "$@") > sift_0
+if ((sift)); then
+    print "${queue[@]}" | aursift -S | cat - <(print "$@") > sift_0
 
-# Note: Exit code of process substitution is ignored.
-while read -r pkg; do
-    warning "no results found for $pkg"
-done < <(
-    grep -Fxvf tsv/pkgname sift_0
-)
+    # Note: Exit code of process substitution is ignored.
+    while read -r pkg; do
+        warning "no results found for $pkg"
+    done < <(grep -Fxvf tsv/pkgname sift_0)
+fi
 
 # Note: Packages without lib32 prefix are not necessarily in the AUR.
-grep -Fxf tsv/pkgname queue_0 | aursift -I | i686 | basesub tsv/pkgbase > queue_1
+grep -Fxf tsv/pkgname <(print "${queue[@]}") | grep -Fxvf <(pacconf IgnorePkg) | awk -v arch="$(uname -m)" '{
+    if(arch == "i686") {
+	gsub(/^lib32-/,""); gsub(/^gcc-multilib$/,"")
+    }; print
+}' | basesub tsv/pkgbase > queue_1
 
 if ((chkver)); then
     # pkgver -> pkgver (sync) -> pkgbase (sync)
