null separation
+check if siftargs is non-empty, as otherwise pacsift lists all cache packages

diff --git a/bin/repofind b/bin/repofind
--- a/bin/repofind
+++ b/bin/repofind
@@ -103,14 +103,18 @@ quickcheck() {
 }
 
 clean() {
-    declare repo siftargs p
-    read -r repo _ < <(reposelect)
+    declare p siftargs
 
-    for p in $(pacman -Slq "$repo"); do
+    for p in $(pacman -Slq "$1"); do
         siftargs+=(--name="$p")
     done
-    
-    pacsift --cache --exact --null "${siftargs[@]}" | sed 's|file://||g' | xargs -r0 sudo rm -vf
+
+    if [[ ${siftargs[@]} ]]; then
+        pacsift --cache --exact --null "${siftargs[@]}" | sed 's|file://||g' | xargs -r0 sudo rm -vf
+    else
+        error "$argv0: invalid argument"
+        exit 22
+    fi
 }
 
 trap 'rm -rf "$tmp"' EXIT
@@ -119,9 +123,9 @@ source /usr/share/makepkg/util.sh || exit
 
 [[ -t 2 ]] && colorize
 
-while getopts :cisu: OPT; do
+while getopts :c:isu: OPT; do
     case $OPT in
-        c|+c) clean      ;;
+        c|+c) clean "$OPTARG" ;;
         i|+i) repofind   ;;
         s|+s) reposelect ;;
         u|+u) quickcheck "$OPTARG" ;;
