stderr

diff --git a/aurclone b/aurclone
--- a/aurclone
+++ b/aurclone
@@ -16,7 +16,7 @@ wait
 fail=($(awk '{if($2 != 0) print $1}' < "$tmp" 2>/dev/null))
 
 if [[ ${fail[@]} ]]; then
-    printf '%s\n' 'Failed to clone:' "${fail[@]}"
+    printf '%s\n' 'Failed to clone:' "${fail[@]}" >&2
 fi
 
 rm "$tmp"
