implement NO_COLOR
This commit replaces AUR_COLOR with NO_COLOR, effectively removing
AUR_COLOR=always.

For simplicity, colors are removed from the plumbing commands as well.

Fixes #585

diff --git a/lib/aur-srcver b/lib/aur-srcver
--- a/lib/aur-srcver
+++ b/lib/aur-srcver
@@ -2,7 +2,6 @@
 # aur-srcver - update and print package revisions
 readonly argv0=srcver
 readonly PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
-readonly AUR_COLOR=${AUR_COLOR-auto}
 
 srcver_pkgbuild_info() {
     env -C "$1" -i bash -c '
@@ -25,16 +24,11 @@ trap_exit() {
 }
 
 usage() {
-    plain 'usage: %s [--noprepare] <pkgbase> [<pkgbase> ...]' "$argv0" >&2
+    printf >&2 'usage: %s [--noprepare] <pkgbase> [<pkgbase> ...]\n' "$argv0"
     exit 1
 }
 
-source /usr/share/makepkg/util/message.sh
 source /usr/share/makepkg/util/parseopts.sh
-
-if [[ ( -t 1 && -t 2 && ! -o xtrace && $AUR_COLOR == auto ) || $AUR_COLOR == always ]] ; then
-    colorize
-fi
 
 opt_short=j:
 opt_long=('no-prepare' 'jobs:')
@@ -96,10 +90,10 @@ for n in "$@"; do
 done
 
 for f in "${failed[@]}"; do
-    warning 'makepkg %s failed for package %s' "${makepkg_args[*]}" "$f"
+    printf >&2 '%s: makepkg %s failed for package %s\n' "$argv0" "${makepkg_args[*]}" "$f"
 
     cat "$tmp/$f"/log >&2
-    plain '8<----'  >&2
+    printf >&2 '8<----\n'
 done
 
 # vim: set et sw=4 sts=4 ft=sh:
diff --git a/lib/aur-sync b/lib/aur-sync
--- a/lib/aur-sync
+++ b/lib/aur-sync
@@ -7,7 +7,6 @@ readonly XDG_CACHE_HOME=${XDG_CACHE_HOME:-$HOME/.cache}
 readonly XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}
 readonly AURDEST=${AURDEST:-$XDG_CACHE_HOME/aurutils/$argv0}
 readonly PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
-readonly AUR_COLOR=${AUR_COLOR-auto}
 
 # default arguments
 build_args=()
@@ -80,8 +79,8 @@ source /usr/share/makepkg/util/util.sh
 source /usr/share/makepkg/util/message.sh
 source /usr/share/makepkg/util/parseopts.sh
 
-if [[ ( -t 1 && -t 2 && ! -o xtrace && $AUR_COLOR == auto ) || $AUR_COLOR == always ]] ; then
-    colorize
+if [[ ! -v NO_COLOR ]] && [[ ! -o xtrace ]]; then
+    [[ -t 2 ]] && colorize
 fi
 
 opt_short='B:C:d:D:M:AcfkLnpPrRsTu'
@@ -162,7 +161,7 @@ if ((rotate)); then
 fi
 
 if ! (($# + update)); then
-    error "$argv0: no targets specified"
+    error '%s: no targets specified' "$argv0"
     exit 1
 fi
 
@@ -177,9 +176,9 @@ aur repo "${repo_args[@]}" --list --status-file=db >db_info
 } <db
 
 if [[ -w $db_root/$db_name.db ]]; then
-    msg "Using [$db_name] repository" >&2
+    msg 'Using [%s] repository' "$db_name" >&2
 else
-    error "$argv0: $db_root/$db_name.db: permission denied"
+    error '%s: %s: permission denied' "$argv0" "$db_root/$db_name.db"
     exit 13
 fi
 
@@ -233,7 +232,7 @@ if order depends >queue_0; then
     tac queue_0 | lib32 | complement filter >queue_1
 else
     # input contains a loop
-    error "$argv0: invalid argument"
+    error '%s: invalid argument' "$argv0"
     exit 22
 fi
 
