aur-sync: return EINVAL if aur-graph fails

diff --git a/lib/aur-sync b/lib/aur-sync
--- a/lib/aur-sync
+++ b/lib/aur-sync
@@ -275,7 +275,10 @@ if ((build)); then
     build_args+=(-a "$tmp"/queue -d "$db_name" -r "$db_root")
 
     # check if dependency graph is valid
-    aur graph "$tmp_view"/*/.SRCINFO >/dev/null
+    if ! aur graph "$tmp_view"/*/.SRCINFO >/dev/null; then
+        error "$argv0: invalid dependency graph"
+        exit 22
+    fi
 
     if ((chroot)); then
         aur build "${build_args[@]}" -- "${makechrootpkg_args[@]}" \
