aur-srcver: check parallel before usage
This way parallel is checked even without specified arguments.

Also rename variables that hold exit codes to be more specific on what
program they concern (here parallel)

diff --git a/lib/aur-srcver b/lib/aur-srcver
--- a/lib/aur-srcver
+++ b/lib/aur-srcver
@@ -34,11 +34,11 @@ trap_exit() {
     fi
 }
 
+command -V parallel >/dev/null || exit
+
 if ((!$#)); then
     usage
 fi
-
-command -V parallel >/dev/null || exit
 
 # XXX trickery for hyphen and absolute path arguments
 mapfile -t arg_path < <(readlink -e -- "$@")
@@ -49,29 +49,29 @@ trap 'trap_exit' EXIT
 cd "$tmp" || exit
 parallel --will-cite --nice 10 -j +2 --joblog makepkg_log --results '{#}_makepkg' \
   'cd {}; makepkg --skipinteg --noprepare -od' >/dev/null 2>&1 ::: "${arg_path[@]}"
-exitcode=$?
+parallel_exit=$?
 
-if ((exitcode > 101)); then
-    printf >&2 '%s: error running "parallel", exit code %d\n' "$argv0" "$exitcode"
-    exit "$exitcode"
+if ((parallel_exit > 101)); then
+    printf >&2 '%s: error running "parallel", exit code %d\n' "$argv0" "$parallel_exit"
+    exit "$parallel_exit"
 fi
 
-if ((exitcode > 0 )); then
-    printf >&2 '%s: failed to update %s packages\n' "$argv0" "$exitcode"
+if ((parallel_exit > 0)); then
+    printf >&2 '%s: failed to update %s packages\n' "$argv0" "$parallel_exit"
 
-    while IFS=$'\t' read -r seq _ _ _ _ _ jobexitcode _ command; do
-        if ((!jobexitcode)); then
-            continue
-        else
+    while IFS=$'\t' read -r seq _ _ _ _ _ job_exit _ command; do
+        if ((job_exit)); then
             printf >&2 '8<----\n'
             printf >&2 '%s\n' "$command"
 
             cat "${seq}_makepkg" >&2
             cat "${seq}_makepkg.err" >&2
+        else
+            continue
         fi
     done < makepkg_log
 
-    exit "$exitcode"
+    exit "$parallel_exit"
 fi
 
 find_pkgbuild_path "${arg_path[@]}" | while IFS= read -d $'\0' -r; do
