aur-fetch: add --sync
Do not make destructive changes in git repositories by default (only run
git fetch), unless --sync is specified. This supersedes the --reset and
--rebase options.

If --confirm-seen is specified, only the AUR_SEEN reference is updated.

diff --git a/lib/aur-fetch b/lib/aur-fetch
--- a/lib/aur-fetch
+++ b/lib/aur-fetch
@@ -11,7 +11,7 @@ pull_args=('--verbose')
 diff_args=('--patch' '--stat')
 
 # default options
-verbose=0 recurse=0 confirm_seen=0 rebase=-1 results=0
+verbose=0 recurse=0 confirm_seen=0 results=0 sync=no
 
 # empty tree object
 git_empty_tree=$(git hash-object -t tree /dev/null)
@@ -32,9 +32,8 @@ if [[ ! -v NO_COLOR ]] && [[ ! -v AUR_DEBUG ]]; then
     [[ -t 2 ]] && colorize
 fi
 
-opt_short='rRvL:'
-opt_long=('recurse' 'verbose' 'write-log:' 'confirm-seen'
-          'rebase' 'reset' 'results:')
+opt_short='rvL:S'
+opt_long=('recurse' 'verbose' 'write-log:' 'confirm-seen' 'sync:' 'results:')
 opt_hidden=('dump-options')
 
 if ! parseopts "$opt_short" "${opt_long[@]}" "${opt_hidden[@]}" -- "$@"; then
@@ -51,10 +50,16 @@ while true; do
             recurse=1 ;;
         -v|--verbose)
             verbose=1 ;;
-        -R|--rebase)
-            rebase=1 ;;
-        --reset)
-            rebase=0 ;;
+        -S)
+            sync=auto ;;
+        --sync)
+            case $2 in
+                auto|reset|rebase|no)
+                    sync=$2 ;;
+                *)
+                    error "$argv0: invalid --sync option"
+                    usage ;;
+            esac ;;
         --confirm-seen)
             confirm_seen=1 ;;
         --results)
@@ -107,7 +112,7 @@ fi | while read -r pkg; do
     export GIT_DIR=$pkg/.git GIT_WORK_TREE=$pkg
 
     # Reset/rebase if we're on valid repo
-    if git rev-parse --git-dir 2>/dev/null; then
+    if git rev-parse --git-dir >/dev/null; then
         if (( confirm_seen )); then
             git update-ref AUR_SEEN HEAD
 
@@ -115,19 +120,25 @@ fi | while read -r pkg; do
             continue # skip diff logic
         fi
 
-        if (( rebase > 0 )) || {
-               (( rebase < 0 )) && [[ $(git config --get --bool aurutils.rebase) == "true" ]]
-           }; then
-            git reset --hard HEAD >&2
+        git fetch --verbose >&2
 
-            if ! git pull --rebase "${pull_args[@]}"; then
-                error '%s: %s: Failed to integrate changes' "$argv0" "$pkg"
-                exit 1
-            fi
-        else
-            git fetch -v >&2
-            git reset --hard 'HEAD@{upstream}' >&2
-        fi
+        case $sync in
+            auto)
+                if [[ $(git config --get --bool aurutils.rebase) == "true" ]]; then
+                    plain 'aurutils.rebase is set for %s' "$pkg"
+                    sync=rebase
+                else
+                    sync=reset
+                fi ;;&
+            rebase)
+                git reset --hard 'HEAD' >&2
+                git rebase "${pull_args[@]}" >&2 ;;
+            reset)
+                git reset --hard 'HEAD@{upstream}' >&2 ;;
+        esac || {
+            error '%s: %s: Failed to integrate changes' "$argv0" "$pkg"
+            exit 1
+        }
 
         if ! seen=$(git rev-parse --quiet --verify AUR_SEEN); then
             warning '%s: AUR_SEEN object not found, assuming empty tree' "$argv0"
@@ -150,6 +161,7 @@ fi | while read -r pkg; do
         if (( results )); then
             printf 'fetch:file://%s\n' "$PWD/$pkg" | tee -a "$results_file"
         fi
+
     # Otherwise, try to clone anew
     elif git clone "$AUR_LOCATION/$pkg".git "$GIT_DIR"; then
         if (( confirm_seen )); then
