repo: refactor
Return to the logic used before commit
fdc4439cbc4f2ce93299e43787d1c62dba573342, with the following changes:

* less stringent error checks (--root matching pacman.conf, --root is a
  directory)
* use aur-repo-parse for read operations, with --list-attr run early
* add --json
* remove --status-file (deprecated in v10)

diff --git a/lib/aur-repo b/lib/aur-repo
--- a/lib/aur-repo
+++ b/lib/aur-repo
@@ -1,32 +1,31 @@
 #!/bin/bash
-# aur-repo - manage local repositories
+# aur-repo - operate on local repositories
 [[ -v AUR_DEBUG ]] && set -o xtrace
 argv0=repo
 PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
 
 # default options
-db_query=local mode=none attr=none list_cols=1,2
+db_query=file mode=none quiet=0 conf_args=() vercmp_args=() list_args=()
 
 usage() {
     printf >&2 'usage: %s [-d repo] [-r path] [-alqtuS]\n' "$argv0"
     exit 1
 }
 
+# option parsing
 source /usr/share/makepkg/util/parseopts.sh
 
-## option parsing
 opt_short='c:d:r:F:alqtuJS'
-opt_long=('config:' 'database:' 'root:' 'all' 'list' 'list-repo' 'list-attr' 'path'
-          'list-path' 'sync' 'upgrades' 'quiet' 'attr:' 'table' 'json')
-opt_hidden=('dump-options' 'repo:' 'repo-list' 'path-list' 'status'
-            'status-file' 'field:')
+opt_long=('config:' 'database:' 'root:' 'all' 'list' 'path' 'list-path' 'list-repo'
+          'list-attr' 'sync' 'upgrades' 'table' 'quiet' 'attr:' 'json')
+opt_hidden=('dump-options' 'repo:' 'repo-list' 'path-list' 'attr-list' 'status' 'field:')
 
 if ! parseopts "$opt_short" "${opt_long[@]}" "${opt_hidden[@]}" -- "$@"; then
     usage
 fi
 set -- "${OPTRET[@]}"
 
-unset mode conf_args db_name db_root vercmp_args attr status_file
+unset mode list db_name db_root status_file pacman_conf vercmp_args attr
 while true; do
     case $1 in
         -d|--database|--repo)
@@ -35,36 +34,32 @@ while true; do
             shift; db_root=$1 ;;
         -c|--config)
             shift; conf_args+=(--config "$1") ;;
-        -q|--quiet)
-            list_cols=1; vercmp_args+=(-q) ;;
-        -S|--sync)
-            db_query=sync ;;
-        -a|--all)
-            mode=upgrades; vercmp_args+=(-a) ;;
-        -u|--upgrades)
-            mode=upgrades ;;
+        -l|--list)
+            mode=list ;;
         -t|--table)
             mode=table ;;
         -J|--json)
             mode=json ;;
+        -a|--all)
+            mode=upgrades; vercmp_args+=(-a) ;;
+        -u|--upgrades)
+            mode=upgrades ;;
+        -q|--quiet)
+            list_args+=(-q); vercmp_args+=(-q) ;;
+        -S|--sync)
+            db_query=sync ;;
         -F|--attr|--field)
             shift; mode=attr; attr=$1 ;;
-        -l|--list)
-            mode=list ;;
-        --list-attr)
-            mode=list_attr ;;
-        --list-path|--path-list)
-            mode=list_path ;;
-        --list-repo|--repo-list)
-            mode=list_repo ;;
         --path)
             mode=path ;;
         --status)
             mode=status ;;
-        --status-file)
-            printf >&2 'deprecation warning: %s --status-file FILE is replaced by aur repo --status >FILE\n' "$argv0"
-            shift; status_file=$1
-            mode=status ;;
+        --path-list|--list-path)
+            list=path ;;
+        --repo-list|--list-repo)
+            list=repo ;;
+        --attr-list|--list-attr)
+            list=attr ;;
         --dump-options)
             printf -- '--%s\n' "${opt_long[@]}" ${AUR_DEBUG+"${opt_hidden[@]}"}
             printf -- '%s' "${opt_short}" | sed 's/.:\?/-&\n/g'
@@ -74,105 +69,115 @@ while true; do
     shift
 done
 
-# Retrieve local repository configuration
-declare -A conf_file_repo conf_sync_repo
-
-while read -r section; do
-    server=$(pacconf "${conf_args[@]}" Server --repo="$section" --single)
-    prefix=${server%://*}
-
-    if [[ $prefix == "file" ]]; then
-        conf_file_repo[$section]=${server#*://}
-    else
-        conf_sync_repo[$section]=$server
-    fi
-done < <(pacconf "${conf_args[@]}" --repo-list)
-wait $! || exit
-
-# List configured local repositories
-if [[ $mode == "list_repo" ]]; then
-    printf '%s\n' "${!conf_file_repo[@]}"
-    exit 0
-elif [[ $mode == "list_path" ]]; then
-    printf '%s\n' "${conf_file_repo[@]}"
-    exit 0
-fi
-
-# Assign environment variables
+# assign environment variables
 : "${db_ext=$AUR_DBEXT}" "${db_name=$AUR_REPO}" "${db_root=$AUR_DBROOT}"
 
-# If no repository is specified on the command-line, assume we want a local
-# repository and try to disambiguate the name.
-if [[ ! $db_name ]]; then
-    if (( ${#conf_file_repo[@]} == 1 )); then
-        db_name=${!conf_file_repo[*]}
+# parse pacman configuration
+unset conf_file_repo conf_file_serv conf_file_path server
 
-    elif (( ${#conf_file_repo[@]} > 1 )); then
-        printf >&2 '%s: repository choice is ambiguous (use -d to specify)\n' "$argv0"
+while read -r key _ value; do
+    case $key=$value in
+        \[*\]*)
+            section=${key:1:-1}
+            ;;
+        DBPath=*)
+            pacman_dbpath=$value
+            ;;
+        Server=file://*)
+            server=${value#file://}
+            conf_file_repo+=("$section")
+            conf_file_serv+=("$server")
+            conf_file_path+=("$server/$section.${db_ext:-db}")
 
-        for repo in "${!conf_file_repo[@]}"; do
-            printf '%q\t%q\n' "$repo" "${conf_file_repo[$repo]}"
-        done | column -o $'\t' -t >&2
-        exit 1
-    else
-        printf >&2 '%s: no file:// repository configured\n' "$argv0"
-        exit 2
-    fi
+            if [[ $section == "$db_name" ]] && [[ ! $db_root ]]; then
+                db_root=$server
+            fi ;;
+        Server=*://*)
+            if [[ $section == "$db_name" ]] && [[ ! $db_root ]]; then
+                db_root=$value
+            fi ;;
+    esac
+done < <(pacman-conf "${conf_args[@]}")
+wait $! || exit
 
-elif [[ $db_query == "local" ]] && [[ ${conf_sync_repo[$db_name]} ]]; then
-    printf >&2 '%s: %s: object is remote (use -S to query)\n' "$argv0" "${conf_sync_repo[$db_name]}"
-    exit 66
-fi
-
-# Default value if -d was specified, but not -r
-# XXX: will be empty for remote repository
-if [[ ! $db_root ]]; then
-    db_root=${conf_file_repo[$db_name]}
-fi
-
-# Process local database directly
-if [[ $db_query == "local" ]]; then
-    db_path=$db_root/$db_name.${db_ext:-db}
-    db_path=$(realpath -- "$db_path") # resolve repo-add symlink
-
-# Process copy (pacman --sync) of remote database
-elif [[ $db_query == "sync" ]]; then
-    pacman_dbpath=$(pacconf "${conf_args[@]}" DBPath) || exit
-    db_path=$pacman_dbpath/sync/$db_name.${db_ext:-db}
-fi
-
-# Basic checks for database
-if [[ ! -f $db_path ]]; then
-    printf >&2 '%s: %s: repository path not found\n' "$argv0" "$db_name"
-    exit 2
-elif [[ $mode == "path" ]]; then
-    printf '%s\n' "$db_path"
-    exit 0
-elif [[ $mode == "status" ]] && [[ -v status_file ]]; then
-    printf 'repo:%s\nroot:%s\npath:%s\n' "$db_name" "$db_root" "$db_path" >"$status_file"
-elif [[ $mode == "status" ]]; then
-    printf 'repo:%s\nroot:%s\npath:%s\n' "$db_name" "$db_root" "$db_path"
-    exit 0
-fi
-
-# Main operations
-set -o pipefail
-case $mode in
+# list information on available local repositories
+case $list in
+    path|repo)
+        if ! (( ${#conf_file_repo[@]} )); then
+            printf >&2 '%s: no file:// repository configured\n' "$argv0"
+            exit 2
+        fi ;;&
+    path)
+        realpath -- "${conf_file_path[@]}" # resolve repo-add symlinks
+        exit 0 ;;
+    repo)
+        printf '%s\n' "${conf_file_repo[@]}"
+        exit 0 ;;
     attr)
-        aur repo-parse -p "$db_path" --attr "$attr" ;;
-    list_attr)
-        aur repo-parse -p "$db_path" --list-attr ;;
-    list)
-        aur repo-parse -p "$db_path" --list | cut -f "$list_cols" ;;
+        aur repo-parse --list-attr 
+        exit ;;
+esac
+
+# select local repository from pacman configuration, if no repository
+# was specified on the command-line
+if ! [[ $db_name ]]; then
+    case ${#conf_file_repo[@]} in
+        1) db_name=${conf_file_repo[0]}
+           db_root=${conf_file_serv[0]}
+           ;;
+        0) printf >&2 '%s: no file:// repository configured\n' "$argv0"
+           exit 2
+           ;;
+        *) printf >&2 '%s: repository choice is ambiguous (use -d to specify)\n' "$argv0"
+
+           for i in "${!conf_file_repo[@]}"; do
+               printf '%q\t%q\n' "${conf_file_repo[$i]}" "${conf_file_path[$i]}"
+           done | column -o $'\t' -t >&2
+           exit 1
+           ;;
+    esac
+fi
+
+# basic file checks
+case $db_query in
+    file)
+        if [[ ! $db_root ]]; then
+            printf >&2 '%s: %s: repository root not found\n' "$argv0" "$db_name"
+            exit 2
+        elif [[ $db_root == *://* ]]; then
+            printf >&2 '%s: %s: object is remote (use -S to query)\n' "$argv0" "$db_root"
+            exit 66
+        fi
+        db_path=$db_root/$db_name.${db_ext:-db}
+        db_path=$(realpath -- "$db_path") # resolve repo-add symlink
+        ;;
+    sync)
+        db_path=$pacman_dbpath/sync/$db_name.${db_ext:-db}
+        ;;
+esac
+
+if [[ ! -f $db_path ]]; then
+    printf >&2 '%s: %s: not a file\n' "$argv0" "$db_path"
+    exit 2
+fi
+
+# database operations
+case $mode in
+    list|table|json)
+        aur repo-parse -p "$db_path" --"$mode" "${list_args[@]}"
+        ;;
     upgrades)
-        aur repo-parse -p "$db_path" --list | aur vercmp "${vercmp_args[@]}" ;;
-    table)
-        aur repo-parse -p "$db_path" --table ;;
-    json)
-        aur repo-parse -p "$db_path" --json ;;
-    *)
-        printf >&2 'error: %s: no mode specified\n' "$argv0"
-        exit 1 ;;
+        aur repo-parse -p "$db_path" --list | aur vercmp "${vercmp_args[@]}"
+        ;;
+    attr)
+        aur repo-parse -p "$db_path" --attr "$attr"
+        ;;
+    path)
+        printf '%s\n' "$db_path"
+        ;;
+    status)
+        printf 'repo:%s\nroot:%s\npath:%s\n' "$db_name" "$db_root" "$db_path"
+        ;;
 esac
 
 # vim: set et sw=4 sts=4 ft=sh:
