fetch: leave heavy lifting to git-pull
Default to running git-pull from origin/master. Specifying the branch
explicitly allows `aur-fetch` to run from other branches (containing
local commits). In case a merge commit is created (--ff --rebase), set
author/committer to aurutils.

The --sync=auto mechanism, which automatically runs git-reset is
removed, and replaced with git-pull without arguments. Latter follows
the `pull.rebase` git-config configuration. Local changes are no longer
automatically discarded, as any conflicts with upstream modifications
should be left to the user.

The --autostash flag (or git-config) can be alternatively be used,
though this may result in non-trivial conflicts when restoring local
changes (see git-pull(1) for details).

diff --git a/lib/aur-fetch b/lib/aur-fetch
--- a/lib/aur-fetch
+++ b/lib/aur-fetch
@@ -6,45 +6,20 @@ AUR_LOCATION=${AUR_LOCATION:-https://aur.archlinux.org}
 XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}
 PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[1]}(): }'
 
+# author information for merge commits
+export GIT_AUTHOR_NAME=aurutils
+export GIT_AUTHOR_EMAIL=aurutils@localhost
+export GIT_COMMITTER_NAME=aurutils
+export GIT_COMMITTER_EMAIL=aurutils@localhost
+
 # default options
-existing=0 recurse=0 sync=no
+existing=0 recurse=0 sync=ffonly
 
 results() {
     local mode=$1 prev=$2 current=$3 path=$4 dest=$5
 
     if [[ -w $dest ]]; then
         printf >> "$dest" '%s:%s:%s:file://%s\n' "$mode" "$prev" "$current" "$path"
-    fi
-}
-
-sync_get_type() {
-    local sync=no key=$1 pkg=$2 head=$3
-
-    if [[ $(git config --get --type bool "$key") == 'true' ]]; then
-        plain >&2 'aurutils.rebase is set for %s' "$pkg"
-
-        if ! git merge-base --is-ancestor 'HEAD@{upstream}' HEAD; then
-            sync=rebase
-        fi
-
-    elif [[ $head != $(git rev-parse --verify 'HEAD@{upstream}') ]]; then
-        sync=reset
-    fi
-
-    printf '%s' "$sync"
-}
-
-sync_merge_revisions() {
-    local sync=$1
-
-    if [[ $sync == 'rebase' ]]; then
-        if [[ $(git config --get --type bool rebase.autoStash) != 'true' ]]; then
-            git reset --hard 'HEAD'
-        fi
-        git rebase --verbose
-
-    elif [[ $sync == 'reset' ]]; then
-        git reset --hard 'HEAD@{upstream}'
     fi
 }
 
@@ -65,33 +40,41 @@ if [[ ! -v NO_COLOR ]] && [[ ! -v AUR_DEBUG ]]; then
 fi
 
 opt_short='rS'
-opt_long=('sync:' 'results:' 'existing' 'recurse')
-opt_hidden=('dump-options')
+opt_long=('no-pull' 'rebase' 'reset' 'merge' 'results:' 'existing' 'recurse'
+          'no-commit' 'autostash')
+opt_hidden=('dump-options' 'sync:' 'auto')
 
 if ! parseopts "$opt_short" "${opt_long[@]}" "${opt_hidden[@]}" -- "$@"; then
     usage
 fi
 set -- "${OPTRET[@]}"
 
-unset results_file
+unset pull_args results_file
 while true; do
     case "$1" in
+        ## fetch options
         --existing)
             existing=1 ;;
-        -S)
-            sync=auto ;;
-        --sync)
-            shift
-            case $1 in
-                auto|reset|rebase|no)
-                    sync=$1 ;;
-                *)
-                    error '%s: invalid --sync option: %s' "$argv0" "$1"
-                    usage ;;
-            esac ;;
+        --no-pull)
+            sync=fetch ;;
+        --reset)
+            sync=reset ;;
+        --rebase)
+            sync=rebase ;;
+        --merge)
+            sync=merge ;;
+        -S|--auto)
+            sync=pull ;; # no default git-pull arguments, checks pull.rebase git config
         --results)
-            shift; results_file=$1 ;;
-        ## deprecated options
+            shift; results_file=$(realpath -- "$1") ;;
+        --sync)
+            shift; sync=$1 ;;
+        ## git-pull options
+        --no-commit)
+            pull_args+=(--no-commit) ;;
+        --autostash)
+            pull_args+=(--autostash) ;;
+        ## other options
         --recurse|-r)
             recurse=1 ;;
         --dump-options)
@@ -103,25 +86,28 @@ while true; do
     shift
 done
 
-# Single hyphen to denote input taken from stdin
-stdin=0
-if (( $# == 1 )) && [[ $1 == "-" || $1 == "/dev/stdin" ]]; then
-    stdin=1
-fi
+case $mode in
+    merge)
+        pull_args+=(--no-rebase) ;;
+    rebase)
+        pull_args+=(--rebase) ;;
+    ffonly)
+        pull_args+=(--ff-only) ;;
+esac
 
 if (( ! $# )); then
-    error '%s: no pkgname given' "$argv0"
+    error '%s: no arguments given' "$argv0"
     exit 1
 fi
 
 if [[ -v results_file ]]; then
-    results_file=$(realpath -- "$results_file")
     : >"$results_file" || exit 1 # truncate file
 fi
 
 if (( recurse )); then
     aur depends --pkgbase "$@" # stdin handled by aur-depends
-elif (( stdin )); then
+
+elif (( $# == 1 )) && [[ $1 == "-" || $1 == "/dev/stdin" ]]; then
     tee # noop
 else
     printf '%s\n' "$@"
@@ -134,47 +120,34 @@ fi | while read -r pkg; do
 
     elif [[ -d $pkg/.git ]]; then
         # Avoid issues with filesystem boundaries (#274)
-        git() { command git -C "$pkg" "$@"; }
+        git() { command git -C "$pkg" "$@" >&2; }
 
-        # Retrieve new upstream revisions. In this step, no commits are merged
-        # to the index and working tree.
-        if git fetch --verbose >&2; then
-            # If upstream has no commits, skip processing the repository. (#959)
-            if fetch_head=$(git rev-parse --verify --quiet FETCH_HEAD); then
-                prev_head=$(git rev-parse --verify --quiet HEAD)
-            else
-                warning '%s: repository has no upstream commits, skipping' "$pkg"
-                continue
-            fi
-
-            if [[ -v results_file ]]; then
-                results 'fetch' "${prev_head:-0}" "$fetch_head" "$PWD/$pkg" "$results_file"
-            fi
-        else
-            error '%s: %s: failed to %s repository' "$argv0" "$pkg" fetch
-            exit 1
-        fi
-
-        if [[ ! $prev_head ]]; then
-            git checkout 'master'
+        # HEAD is assumed to point to a valid commit
+        if ! prev_head=$(git rev-parse --verify --quiet HEAD); then
+            warning '%s: %s: HEAD not found, skipping repository' "$argv0" "$pkg"
             continue
         fi
 
-        if [[ $sync == 'auto' ]]; then
-            # sync = rebase, reset or no
-            sync=$(sync_get_type aurutils.rebase "$pkg" "$prev_head")
-        fi
-
-        # Merge revisions in the master branch with upstream.
-        if sync_merge_revisions "$sync" >&2; then
-            head=$(git rev-parse --verify HEAD)
-
-            if [[ -v results_file ]] && [[ $sync != 'no' ]]; then
-                results "$sync" "$prev_head" "$head" "$PWD/$pkg" "$results_file"
-            fi
-        else
-            error '%s: %s: failed to %s repository' "$argv0" "$pkg" "$sync"
+        # Merge in new history
+        ref=0
+        case $sync in
+            pull|rebase|merge|ffonly)
+                ref='HEAD'
+                git pull origin master "${pull_args[@]}" -v ;;
+            fetch)
+                ref='FETCH_HEAD'
+                git fetch origin -v ;;
+            reset)
+                ref='master@{upstream}'
+                git fetch origin -v && git reset --hard "$ref" ;;
+        esac || {
+            error '%s: %s: --sync=%s failed' "$argv0" "$pkg" "$sync"
             exit 1
+        }
+
+        if [[ -v results_file ]]; then
+            commit=$(git rev-parse --verify "$ref")
+            results "$sync" "$prev_head" "$commit" "$PWD/$pkg" "$results_file"
         fi
 
     # Otherwise, try to clone anew
