fetch: use regular printf instead of message.sh

diff --git a/lib/aur-fetch b/lib/aur-fetch
--- a/lib/aur-fetch
+++ b/lib/aur-fetch
@@ -32,16 +32,11 @@ usage() {
 ICAgICAgICAgICAgIC4tLX5+LF9fCjotLi4uLiwtLS0tLS0tYH5+Jy5fLicKIGAtLCwsICAs
 XyAgICAgIDsnflUnCiAgXywtJyAsJ2AtX187ICctLS4KIChfLyd+fiAgICAgICcnJycoOwoK
 !
-    plain >&2 'usage: %s [-S] [--] pkgname...' "$argv0"
+    printf >&2 'usage: %s [-S] [--] pkgname...\n' "$argv0"
     exit 1
 }
 
-source /usr/share/makepkg/util/message.sh
 source /usr/share/makepkg/util/parseopts.sh
-
-if [[ ! -v NO_COLOR ]] && [[ ! -v AUR_DEBUG ]]; then
-    [[ -t 2 ]] && colorize
-fi
 
 opt_short='rS'
 opt_long=('existing' 'fetch-only' 'reset' 'rebase' 'results:' 'discard'
@@ -100,12 +95,12 @@ if [[ $sync == 'auto' ]]; then
     discard=1; sync=merge
 
 elif [[ $sync == !(merge|rebase|reset|fetch) ]]; then
-    error '%s: invalid --sync mode' "$argv0"
+    printf >&2 '%s: error: invalid --sync mode\n' "$argv0"
     exit 1
 fi
 
 if (( ! $# )); then
-    error '%s: no arguments given' "$argv0"
+    printf >&2 '%s: error: no arguments given\n' "$argv0"
     exit 1
 fi
 
@@ -130,7 +125,7 @@ fi | while read -r pkg; do
 
     # Verify if the repository is hosted on AUR (#959)
     if (( existing )) && ! git ls-remote --exit-code "$AUR_LOCATION/$pkg" >/dev/null; then
-        warning '%s: package is not in AUR, skipping' "$argv0" "$pkg"
+        printf >&2 '%s: warning: package %s is not in AUR, skipping\n' "$argv0" "$pkg"
         continue
 
     elif [[ -d $pkg/.git ]]; then
@@ -166,7 +161,7 @@ fi | while read -r pkg; do
             # Leave branch untouched
             dest='master@{u}'
         fi >&2 || {
-            error '%s: %s: failed to %s repository' "$argv0" "$pkg" "$sync"
+            printf >&2 '%s: error: failed to %s repository %s\n' "$argv0" "$sync" "$pkg"
             exit 1
         }
 
@@ -185,7 +180,7 @@ fi | while read -r pkg; do
             results 'clone' "$git_empty_object" "${head:-$git_empty_object}" "$PWD/$pkg" "$results_file"
         fi
     else
-        error '%s: %s: failed to clone repository' "$argv0" "$pkg"
+        printf >&2 '%s: error: failed to clone repository %s\n' "$argv0" "$pkg"
         exit 1
     fi
 done
