srcver: exit 1 if any makepkg job failed
/usr/share/makepkg/util/error.sh defines E_FAIL=1 as "generic error".

diff --git a/lib/aur-srcver b/lib/aur-srcver
--- a/lib/aur-srcver
+++ b/lib/aur-srcver
@@ -161,4 +161,8 @@ for i in "${!failed[@]}"; do
     printf >&2 '8<----\n'
 done
 
+if (( ${#failed[@]} )); then
+    exit 1 # E_FAIL
+fi
+
 # vim: set et sw=4 sts=4 ft=sh:
