fetch: simplify "pull --rebase" fail check
`git pull --rebase` already exits with error when it fails to apply the
changes. This means that our current check is unreachable and
unnecessary.

`git` itself already prints advice on how to proceed, so let's simplify
the check and only print a small message to make a bit more clear which
package caused the failure.

diff --git a/lib/aur-fetch b/lib/aur-fetch
--- a/lib/aur-fetch
+++ b/lib/aur-fetch
@@ -91,10 +91,8 @@ fi | while read -r pkg; do
 
         # Discard any local uncommited changes. (#552)
         git reset --hard HEAD >&2
-        git pull --rebase "${fetch_args[@]}" || exit 1
-
-        if ! git diff-files --diff-filter=U --quiet; then
-            warning '%s: Local commits conflict with upstream. Fix the conflicts and commit them.' "$pkg"
+        if ! git pull --rebase "${fetch_args[@]}"; then
+            error '%s: Failed to integrate changes.' "$pkg"
             exit 1
         fi
 
