srcver: accept arbitrary directory paths
This makes the input arguments more in line with aur-build.

Argument paths are resolved with realpath(1), as two paths can point to the
same directory (e.g.  foo and ./foo).

diff --git a/lib/aur-srcver b/lib/aur-srcver
--- a/lib/aur-srcver
+++ b/lib/aur-srcver
@@ -73,10 +73,6 @@ if (( $# == 1 )) && [[ $1 == "-" || $1 == "/dev/stdin" ]]; then
     stdin=1
 fi
 
-if (( ! $# )); then
-    usage
-fi
-
 # shellcheck disable=SC2174
 mkdir -pm 0700 -- "${TMPDIR:-/tmp}/aurutils-$UID"
 tmp=$(mktemp -d --tmpdir "aurutils-$UID/$argv0.XXXXXXXX") || exit
@@ -89,36 +85,43 @@ trap 'trap_exit' EXIT
 if (( stdin )); then
     mapfile -t packages
 else
-    packages=("$@")
+    packages=("${@:-$PWD}")
     set --
 fi
 
+# Remove duplicates in pkgbuild dirs
+declare -A seen
+
 i=0 # package counter
 for n in "${packages[@]}"; do
+    n=$(realpath "$n"); [[ ${seen[$n]} ]] && continue
+    seen[$n]=1
+
     if (( i++ >= num_procs )); then
         wait -n
     fi
 
-    { mkdir -p -- "$tmp/$n"
+    { mkdir -p -- "$tmp/$i"
+      echo "$n" > "$tmp/$i"/path
 
-      if ! env -C "$n" nice -n 20 makepkg "${makepkg_args[@]}" >"$tmp/$n"/log 2>&1; then
-          echo $? >"$tmp/$n"/failed
+      if ! env -C "$n" nice -n 20 makepkg "${makepkg_args[@]}" >"$tmp/$i"/log 2>&1; then
+          echo $? >"$tmp/$i"/failed
       fi
     } &
 done
 wait
 
-failed=()
+declare -A failed
 for d in "$tmp"/*/; do # iterate over directories
-    n=$(basename "$d")
+    i=$(basename "$d") p=$(<"$d"/path)
 
-    if [[ -e $tmp/$n/failed ]]; then
-        failed+=("$n")
+    if [[ -e $d/failed ]]; then
+        failed[$i]=$p
     else
         # Precautions when sourcing the PKGBUILD have no effect here,
         # because makepkg already sourced the PKGBUILD above.
         # shellcheck disable=SC1090
-        ( source "$n/${buildscript-PKGBUILD}"
+        ( source "$p/${buildscript-PKGBUILD}"
 
           fullver=$(get_full_version)
           printf '%s\t%s\n' "${pkgbase:-$pkgname}" "$fullver"
@@ -130,10 +133,10 @@ if (( ${#failed[@]} )); then
     printf >&2 '8<----\n'
 fi
 
-for f in "${failed[@]}"; do
-    printf >&2 '%s: makepkg %s failed for package %s\n' "$argv0" "${makepkg_args[*]}" "$f"
+for i in "${!failed[@]}"; do
+    printf >&2 '%s: makepkg %s failed for path %s\n' "$argv0" "${makepkg_args[*]}" "${failed[$i]}"
 
-    cat "$tmp/$f"/log >&2
+    cat "$tmp/$i"/log >&2
     printf >&2 '8<----\n'
 done
 
