aur-fetch: add --rebase, --reset

diff --git a/lib/aur-fetch b/lib/aur-fetch
--- a/lib/aur-fetch
+++ b/lib/aur-fetch
@@ -6,19 +6,21 @@ AUR_LOCATION=${AUR_LOCATION:-https://aur.archlinux.org}
 XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}
 PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[1]}(): }'
 
-# default options
-verbose=0 recurse=0 fetch_args=('--verbose') confirm_seen=0
+# default arguments
+pull_args=('--verbose')
 
-gen_patchfile() {
-    git diff-tree --patch --stat "${2:-$(git hash-object -t tree /dev/null)}" "$1"
-}
+# default options
+verbose=0 recurse=0 confirm_seen=0 rebase=-1
+
+# empty tree object
+git_empty_tree=$(git hash-object -t tree /dev/null)
 
 usage() {
     cat <<! | base64 -d
 ICAgICAgICAgICAgIC4tLX5+LF9fCjotLi4uLiwtLS0tLS0tYH5+Jy5fLicKIGAtLCwsICAs
 XyAgICAgIDsnflUnCiAgXywtJyAsJ2AtX187ICctLS4KIChfLyd+fiAgICAgICcnJycoOwoK
 !
-    plain 'usage: %s [-L directory] [-rv] pkgname...' "$argv0" >&2
+    plain >&2 'usage: %s [-L directory] [-frv] pkgname...' "$argv0"
     exit 1
 }
 
@@ -29,8 +31,9 @@ if [[ ! -v NO_COLOR ]] && [[ ! -v AUR_DEBUG ]]; then
     [[ -t 2 ]] && colorize
 fi
 
-opt_short='rvL:'
-opt_long=('recurse' 'verbose' 'write-log:' 'force' 'confirm-seen')
+opt_short='frRvL:'
+opt_long=('recurse' 'verbose' 'write-log:' 'force' 'confirm-seen'
+          'rebase' 'reset')
 opt_hidden=('dump-options')
 
 if ! parseopts "$opt_short" "${opt_long[@]}" "${opt_hidden[@]}" -- "$@"; then
@@ -47,12 +50,16 @@ while true; do
             recurse=1 ;;
         -v|--verbose)
             verbose=1 ;;
+        -R|--rebase)
+            rebase=1 ;;
+        --reset)
+            rebase=0 ;;
         --force)
             fetch_args+=('--force') ;;
         --confirm-seen)
             confirm_seen=1 ;;
         --dump-options)
-            printf -- '--%s\n' "${opt_long[@]}" 
+            printf -- '--%s\n' "${opt_long[@]}"
             printf -- '%s' "${opt_short}" | sed 's/.:\?/-&\n/g'
             exit ;;
         --) shift; break ;;
@@ -70,67 +77,95 @@ if ! (( $# )); then
     exit 1
 fi
 
-# Prepare configuration directory.
-mkdir -p "$XDG_CONFIG_HOME"/aurutils/$argv0
-
-# Default to showing PKGBUILD first in patch. (#399)
-orderfile=$XDG_CONFIG_HOME/aurutils/$argv0/orderfile
-
-if [[ ! -s $orderfile ]]; then
-    printf 'PKGBUILD\n' > "$orderfile"
+if (( confirm_seen )); then
+    msg 'Marking repositories as seen' >&2
 fi
 
-if (( confirm_seen )); then
-    msg "Marking repositories as seen"
+# Default to showing PKGBUILD first in patch. (#399)
+mkdir -p "$XDG_CONFIG_HOME/aurutils/$argv0"
+orderfile=$XDG_CONFIG_HOME/aurutils/$argv0/orderfile
+
+if ! [[ -s $orderfile ]]; then
+    printf 'PKGBUILD\n' >"$orderfile"
 fi
 
 if (( recurse )); then
     aur depends --pkgbase "$@"
 else
-   printf '%s\n' "$@"
+    printf '%s\n' "$@"
 fi | while read -r pkg; do
-    if [[ ! -e $pkg ]]; then
-        if git clone "$AUR_LOCATION"/"$pkg".git; then
-            # show PKGBUILDS first (#399)
-            git -C "$pkg" config diff.orderFile "$orderfile"
-            # only allow fast-forward fetches. (#)
-            git -C "$pkg" config remote.origin.fetch 'refs/heads/*:refs/remotes/origin/*'
-        else
+    # Avoid issues with filesystem boundaries. (#274)
+    export GIT_DIR=$pkg/.git GIT_WORK_TREE=$pkg
+
+    if ! [[ -e $pkg ]]; then
+        if ! git clone "$AUR_LOCATION/$pkg".git "$GIT_DIR"; then
             error '%s: %s: Failed to clone repository' "$argv0" "$pkg"
             exit 1
         fi
-    fi
-    # Avoid issues with filesystem boundaries, (#274)
-    # and make sure we have a valid git repository.
-    GIT_DIR=$(git rev-parse --resolve-git-dir "$pkg"/.git) || exit
-    export GIT_DIR GIT_WORK_TREE=$pkg
 
-    if (( confirm_seen )); then
-        git update-ref AURUTILS_SEEN HEAD
-        msg2 'Marked %s as seen' "$pkg"
-        continue
-    fi
+        # Show PKGBUILDs first. (#399)
+        git config diff.orderFile "$orderfile"
 
-    # Discard any local uncommited changes. (#552)
-    git reset --hard HEAD >&2
-    if ! git pull --rebase "${fetch_args[@]}"; then
-        error '%s: Failed to integrate changes.' "$pkg"
-        exit 1
+        if (( confirm_seen )); then
+            git update-ref AURUTILS_SEEN HEAD
+
+            warning 'Marked new repository %s as seen' "$pkg"
+            continue # skip diff logic
+        else
+            # Set marker to empty tree object.
+            git update-ref AURUTILS_SEEN "$git_empty_tree"
+
+            # This case may be handled differently from an existing repo where
+            # the AURUTILS_SEEN ref does not exist; here, we know that the repo
+            # is at the current HEAD, and a git pull is not required.
+            : cloned repository was not inspected
+        fi
+    else
+        # Ensure a valid git repository. (#586)
+        if ! git rev-parse --git-dir; then
+            # The original git rev-parse exit code on a malformed git
+            # repository is 128, or EKEYREVOKED in errno.h.
+            exit 1
+        fi
+
+        if (( confirm_seen )); then
+            git update-ref AURUTILS_SEEN HEAD
+
+            msg2 'Marked %s as seen' "$pkg" >&2
+            continue
+        fi
+
+        if (( rebase > 0 )) || {
+               (( rebase < 0 )) && [[ $(git config --get --bool aurutils.rebase) == "true" ]]
+           }; then
+            git reset --hard HEAD >&2
+
+            if ! git pull --rebase "${pull_args[@]}"; then
+                error '%s: %s: Failed to integrate changes' "$argv0" "$pkg"
+                exit 1
+            fi
+        else
+            git fetch -v >&2
+            git reset --hard 'HEAD@{upstream}' >&2
+        fi
     fi
 
     seen=$(git rev-parse --quiet --verify AURUTILS_SEEN)
 
-    if [[ "$seen" != $(git rev-parse HEAD) ]]; then
-        log_range=(HEAD ${seen:+^$seen})
+    if [[ -z $seen ]]; then
+        #seen=$git_empty_tree
+        warning '%s: AURUTILS_SEEN object not found, assuming empty tree' "$argv0"
+    fi
 
+    # Directory was inspected (--confirm-seen) at a previous time.
+    if [[ $seen != "$(git rev-parse HEAD)" ]]; then
+        # Contents have changed since last inspection; print differences.
         if (( verbose )); then
-            gen_patchfile "${log_range[@]}"
+            git --no-pager log --patch --stat "${seen:+$seen..}HEAD"
         fi
 
         if [[ $log_dir ]]; then
-            logfile="$log_dir/$pkg".patch
-            gen_patchfile "${log_range[@]}" >"$logfile"
-            plain '%s' "$logfile"
+            git --no-pager log --patch --stat "${seen:+$seen..}HEAD" >"$log_dir/$pkg".diff
         fi
     fi
 done
