remove redundant printf EOF
Only required when the format string begins with a hyphen.

$ printf -foo
-bash: printf: -f: invalid option
printf: usage: printf [-v var] format [arguments]

$ printf '%s\n' -foo
-foo

$ unknown=--someoption
$ printf "$unknown%s\n" bar
-bash: printf: --: invalid option
printf: usage: printf [-v var] format [arguments]

$ printf -- "$unknown%s\n" bar
--someoptionbar

$ printf "%s$unknown\n" bar
bar--someoption

diff --git a/lib/aur-pkglist b/lib/aur-pkglist
--- a/lib/aur-pkglist
+++ b/lib/aur-pkglist
@@ -20,7 +20,7 @@ list_update() {
     if wget -O - -o last_transfer "$1" | gzip -d - > "$2"; then
         extract_date "$2"
     else
-        printf -- >&2 'warning: failed to retrieve package list\n'
+        printf >&2 'warning: failed to retrieve package list\n'
     fi
 }
 
@@ -28,12 +28,12 @@ list_http_date() {
     if wget -S --spider -o last_transfer "$1"; then
         awk -F', ' '/Date:/ {print $2}' last_transfer
     else
-        printf -- >&2 'warning: failed to retrieve HTTP date\n'
+        printf >&2 'warning: failed to retrieve HTTP date\n'
     fi
 }
 
 usage() {
-    printf -- >&2 'usage: %s: [-bt] [-FP pattern]\n' "$argv0"
+    printf >&2 'usage: %s: [-bt] [-FP pattern]\n' "$argv0"
     exit 1
 }
 
