aur-repo-filter: replace expac with pacinfo
Recent versions of pacinfo have an easy to parse, line-by-line format,
removing the need for expac. Newline seperation should suffice, so
remove --null.

This could be used to implement --sysroot, which is however blocked by a
pacsift bug:

https://github.com/andrewgregory/pacutils/issues/26

diff --git a/lib/aur-repo-filter b/lib/aur-repo-filter
--- a/lib/aur-repo-filter
+++ b/lib/aur-repo-filter
@@ -6,19 +6,17 @@ readonly arch_repo=(core extra testing community{,-testing} multilib{,-testing})
 
 # The command line will hit ARG_MAX on approximately 70k packages;
 # spread arguments with xargs (and printf, as a shell built-in).
-print_args() {
-    printf -- '--satisfies=%s\n' "$@"
-}
-
 satisfies() {
     #global sift_args
-    xargs -a <(print_args "$@") pacsift --null "${sift_args[@]}" <&-
+    xargs -a <(printf -- '--satisfies=%s\n' "$@") pacsift "${sift_args[@]}" <&-
 }
 
-# Use null delimimitation as repository names may contain (apart from
-# newlines) arbitrary characters.
 provides() {
-    xargs -0r expac '%n %R %S' -Sv
+    pacinfo | awk -F'[:<=>]' '
+        /Name:/     { pkgname=$2; print $2, $2; }
+        /Provides:/ { print pkgname, $2; }
+        /Replaces:/ { print pkgname, $2; }
+    '
 }
 
 usage() {
@@ -54,6 +52,11 @@ while true; do
     esac
     shift
 done
+
+if ! [[ -e ${sysroot}/etc/pacman.conf ]]; then
+    error "$argv0: invalid sysroot (${sysroot}/etc/pacman.conf does not exist)"
+    exit 2
+fi
 
 if ((sync_repo)); then
     sift_args+=(--sync)
@@ -98,30 +101,25 @@ fi
 
 # Standard input is taken as "provides[<cmp><version>]", where pacsift
 # checks for a package satisfying this condition. Results are printed
-# as "repository/package", and piped to expac to relate the names of
+# as "repository/package", and piped to pacinfo to relate the names of
 # the original provides to its corresponding package(s).
-satisfies "${strset[@]}" | provides | while read -ra array; do
-    package=${array[0]}
-
+satisfies "${strset[@]}" | provides | while read -r package virtual; do
     if [[ ${pkgset[$package]} ]]; then
         printf '%s\n' "$package"
     fi
 
-    for ((i = 1; i < ${#array[@]}; i++)); do
-        virtual=${array[$i]}
+    if [[ $virtual != "$package" ]]; then
+        version=${pkgset[$virtual]}
+    else
+        continue
+    fi
 
-        case $virtual in
-            None) continue ;;
-               *) version=${pkgset[$virtual]} ;;
-        esac
-
-        case $version in
-            1) plain "dependency $virtual satisfied by $package" >&2
-               printf '%s\n' "$virtual" ;;
-            *) plain "dependency $virtual$version satisfied by $package" >&2
-               printf '%s\n' "$virtual" ;;
-        esac
-    done
+    case $version in
+        1) plain "dependency $virtual satisfied by $package" >&2
+           printf '%s\n' "$virtual" ;;
+        *) plain "dependency $virtual$version satisfied by $package" >&2
+           printf '%s\n' "$virtual" ;;
+    esac
 done
 
 # vim: set et sw=4 sts=4 ft=sh:
