search: add --color
Setting `--color=auto` or `--color=none` is particularly useful when
redirecting formatted output to a file.

diff --git a/lib/aur-search b/lib/aur-search
--- a/lib/aur-search
+++ b/lib/aur-search
@@ -123,15 +123,8 @@ usage() {
 source /usr/share/makepkg/util/message.sh
 source /usr/share/makepkg/util/parseopts.sh
 
-if [[ ! -v NO_COLOR ]] && [[ ! -v AUR_DEBUG ]]; then
-    # We use colored messages on both stdout and stderr, and these may
-    # be desired even if stdout is not connected to a terminal. (in
-    # particular, aur search foo | less -R, #585)
-    colorize
-fi
-
 opt_short='k:adimnqrsv'
-opt_long=('any' 'info' 'search' 'desc' 'maintainer' 'name' 'depends' 'verbose'
+opt_long=('any' 'info' 'search' 'desc' 'maintainer' 'name' 'depends' 'verbose' 'color:'
           'makedepends' 'optdepends' 'checkdepends' 'key:' 'short' 'table' 'json')
 opt_hidden=('dump-options' 'raw' 'json-stdin')
 
@@ -163,6 +156,8 @@ while true; do
             search_by=optdepends ;;
         --checkdepends)
             search_by=checkdepends ;;
+        --color)
+            shift; color=$1 ;;
         -q|--short)
             format=short ;;
         -v|--verbose)
@@ -184,7 +179,24 @@ while true; do
     shift
 done
 
-if ! (( $# )) && ! [[ $mode == "stdin_json" || $mode == "stdin_table" ]]; then
+# Colored messages on both stdout and stderr may be desired if stdout is not
+# connected to a terminal, e.g. when piping to less -R. (#585) When printing to
+# a file, they should be disabled instead. Default to `--color=auto` but allow
+# specifying other modes.
+if [[ ! -v NO_COLOR ]] && [[ ! -v AUR_DEBUG ]]; then
+    if [[ $color == 'auto' ]]; then
+        [[ -t 1 ]] && colorize
+
+    elif [[ $color == 'always' ]]; then
+        colorize
+
+    elif [[ $color != 'none' ]]; then
+        printf >&2 '%s: invalid --color mode\n' "$argv0"
+        exit 1
+    fi
+fi
+
+if ! (( $# )) && ! [[ $mode == "json_stdin" ]]; then
     usage
 fi
 
