aur-sync: use function for aur-graph block

diff --git a/lib/aur-sync b/lib/aur-sync
--- a/lib/aur-sync
+++ b/lib/aur-sync
@@ -57,6 +57,12 @@ complement() {
     grep -Fxvf "$@" || return $(( $? - 1 ))
 }
 
+srcinfo_graph() {
+    while read -r pkg; do
+        [[ $pkg ]] && printf '%s\0' "$pkg/.SRCINFO"
+    done | xargs -0 cat -- | aur graph >/dev/null
+}
+
 trap_exit() {
     if [[ ! -v AUR_DEBUG ]]; then
         rm -rf -- "$tmp"
@@ -356,15 +362,9 @@ if (( download )); then
 fi
 
 # Verify dependency tree (#20)
-if (( graph )); then
-    if ! { while read -r pkg; do
-               [[ $pkg ]] && printf '%s\0' "$pkg/.SRCINFO"
-           done | xargs -0 cat -- | aur graph >/dev/null
-         }
-    then
-        error '%s: failed to verify dependency graph' "$argv0"
-        exit 1
-    fi < "$tmp"/queue
+if (( graph )) && ! srcinfo_graph < "$tmp"/queue; then
+    error '%s: failed to verify dependency graph' "$argv0"
+    exit 1
 fi
 
 # Inspect package files
