aur-srcver: add usage, message.sh, --no-prepare
Similar to other scripts (`aur-sync`, `aur-chroot`), `--no-foo` is an alias to `--nofoo`. Show the hyphen-seperated option in the shell completion.

diff --git a/lib/aur-srcver b/lib/aur-srcver
--- a/lib/aur-srcver
+++ b/lib/aur-srcver
@@ -5,28 +5,6 @@ readonly PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
 readonly startdir=$PWD
 makepkg_args=('--nobuild' '--nodeps' '--skipinteg')
 
-source /usr/share/makepkg/util/parseopts.sh
-opt_short=
-opt_long=('noprepare')
-opt_hidden=('dump-options')
-if ! parseopts "$opt_short" "${opt_long[@]}" "${opt_hidden[@]}" -- "$@"; then
-    echo "usage: $argv0 [--noprepare] <pkgbase> [<pkgbase> ...]" >&2
-    exit 1
-fi
-set -- "${OPTRET[@]}"
-unset opt_short opt_long opt_hidden OPTRET
-
-while true; do
-    case "$1" in
-        --noprepare)    makepkg_args+=("$1") ;;
-        --dump-options) printf -- '--%s\n' "${opt_long[@]}"
-                        printf -- '%s' "${opt_short}" | sed 's/.:\?/-&\n/g'
-                        exit ;;
-        --) shift; break ;;
-    esac
-    shift
-done
-
 srcver_pkgbuild_info() {
     env -C "$1" -i bash -c '
         PATH= source PKGBUILD
@@ -57,9 +35,41 @@ trap_exit() {
     fi
 }
 
-if ! (($#)); then
-    printf >&2 'usage: %s path...\n' "$argv0"
+usage() {
+    plain "usage: $argv0 [--noprepare] <pkgbase> [<pkgbase> ...]" >&2
     exit 1
+}
+
+source /usr/share/makepkg/util/message.sh
+source /usr/share/makepkg/util/parseopts.sh
+
+if [[ -t 2 && ! -o xtrace ]]; then
+    colorize
+fi
+
+opt_short=
+opt_long=('no-prepare')
+opt_hidden=('dump-options' 'noprepare')
+
+if ! parseopts "$opt_short" "${opt_long[@]}" "${opt_hidden[@]}" -- "$@"; then
+    usage
+fi
+set -- "${OPTRET[@]}"
+unset opt_short opt_long opt_hidden OPTRET
+
+while true; do
+    case "$1" in
+        --noprepare|--no-prepare) makepkg_args+=(--noprepare) ;;
+        --dump-options) printf -- '--%s\n' "${opt_long[@]}"
+			printf -- '%s' "${opt_short}" | sed 's/.:\?/-&\n/g'
+			exit ;;
+        --) shift; break ;;
+    esac
+    shift
+done
+
+if ! (($#)); then
+    usage
 fi
 
 tmp=$(mktemp -dt "$argv0".XXXXXXXX) || exit
@@ -70,12 +80,12 @@ aur jobs --nice 10 -j +2 --joblog "$tmp"/makepkg_log --results "$tmp/{#}_makepkg
 jobs_exit=$?
 
 if ((jobs_exit > 101)); then
-    printf >&2 '%s: error running "parallel", exit code %d\n' "$argv0" "$jobs_exit"
+    error "$argv0: error running 'parallel', exit code $jobs_exit"
     exit "$jobs_exit"
 fi
 
 if ((jobs_exit > 0)); then
-    printf >&2 '%s: failed to update %s packages\n' "$argv0" "$jobs_exit"
+    error "$argv0: failed to update $jobs_exit packages"
 
     while IFS=$'\t' read -r seq _ _ _ _ _ makepkg_exit _ command; do
         if ((makepkg_exit)); then
