pkglist: write last_transfer

diff --git a/lib/aur-pkglist b/lib/aur-pkglist
--- a/lib/aur-pkglist
+++ b/lib/aur-pkglist
@@ -16,16 +16,20 @@ extract_date() {
 readonly -f extract_date
 
 list_update() {
-    if wget -q "$1" -O - | gzip -d - > "$2"; then
+    if wget -O - -o last_transfer "$1" | gzip -d - > "$2"; then
         extract_date "$2"
     else
-        printf >&2 '%s\n' 'warning: failed to retrieve package list'
+        printf >&2 'warning: failed to retrieve package list\n'
     fi
 }
 readonly -f list_update
 
 list_http_date() {
-    curl -fsSI "$1" | awk -F', ' 'tolower($1) ~ /^date:/ {print $2}'
+    if wget -S --spider -o last_transfer "$1"; then
+        awk -F', ' '/Date:/ {print $2}' last_transfer
+    else
+        printf >&2 'warning: failed to retrieve HTTP date\n'
+    fi
 }
 readonly -f list_http_date
 
