build--pkglist: check if --user is unprivileged

diff --git a/lib/aur-build--pkglist b/lib/aur-build--pkglist
--- a/lib/aur-build--pkglist
+++ b/lib/aur-build--pkglist
@@ -52,12 +52,12 @@ while true; do
 done
 
 # drop permissions for sourcing PKGBUILDs
-if (( UID == 0 )) && [[ -v build_user ]]; then
+if (( UID == 0 )) && [[ -v build_user ]] && (( $(id -u "$build_user") != 0 )); then
     exec setpriv --reuid "$build_user" --regid "$build_user" --init-groups --reset-env \
          env PKGDEST="$PKGDEST" "${BASH_SOURCE[0]}" "${orig_argv[@]}"
 
 elif (( UID == 0 )); then
-    printf >&2 '%s: --user required\n' "$argv0"
+    printf >&2 '%s: unprivileged --user required\n' "$argv0"
     exit 1
 fi
 
