aur-query: exit 1 if parallel transfer failed
curl will exit 0 regardless of any transfers failed with curl --parallel
(including when --fail-early is specified), so some trickery with
--stderr is required.

diff --git a/lib/aur-query b/lib/aur-query
--- a/lib/aur-query
+++ b/lib/aur-query
@@ -99,31 +99,44 @@ Warning: Press CTRL-D to exit.
 EOF
 fi
 
-# pipeline
-readarray -t urls < <(jq -R -r '@uri' | uri_write)
-
+# generate curl config
 if (( AUR_QUERY_PARALLEL )); then
     mkdir "$tmp"/out
-    counter=0
+    unset i
 
-    for uri in "${urls[@]}"; do
-        counter=$((counter+1))
+    jq -R -r '@uri' | uri_write | while IFS= read -r uri; do
+        i=$((i+1))
 
         printf 'url %s\n' "$uri"
-        printf 'output %q\n' "$tmp/out/$counter"
-    done > "$tmp"/par_config
+        printf 'output %q\n' "$tmp/out/$i"
+    done > "$tmp"/config
 
-    if [[ -s $tmp/par_config ]]; then
-        curl -K "$tmp"/par_config "${curl_args[@]}" \
-             --parallel --parallel-max "$AUR_QUERY_PARALLEL_MAX" || exit
-    fi
+else
+    jq -R -r '@uri' | uri_write | while IFS= read -r uri; do
+        printf 'url "%s"\n' "$uri"
+    done > "$tmp"/config
+fi
 
-    if [[ -f $tmp/out/1 ]]; then
+# exit cleanly on empty input (#706)
+if [[ ! -s $tmp/config ]]; then
+    exit
+fi
+
+if (( AUR_QUERY_PARALLEL )); then
+    # support parallel transfers (curl >7.66.0)
+    curl "${curl_args[@]}" -K "$tmp"/config --stderr "$tmp"/error \
+         --parallel --parallel-max "$AUR_QUERY_PARALLEL_MAX"
+
+    # curl --parallel does not exit >0 on failed transfers, thus
+    # stderr has to be checked manually
+    if (( $? )) || [[ -s $tmp/error ]]; then
+        sort "$tmp"/error | uniq -c >&2
+        exit 1
+    else
         cat "$tmp"/out/*
     fi
-
-elif (( ${#urls[@]} )); then
-    printf 'url "%s"\n' "${urls[@]}" | curl -K- "${curl_args[@]}"
+else
+    curl "${curl_args[@]}" -K "$tmp"/config
 fi
 
 # vim: set et sw=4 sts=4 ft=sh:
