scripts: style changes
Of note: the order function hardcoded "depends" all along...

diff --git a/lib/aur-sync b/lib/aur-sync
--- a/lib/aur-sync
+++ b/lib/aur-sync
@@ -58,10 +58,6 @@ complement() {
     grep -Fxvf "$@" || return $(( $? - 1 ))
 }
 
-order() {
-    cut -f1,2 depends | tr_ver | tsort
-}
-
 trap_exit() {
     if [[ ! -v AUR_DEBUG ]]; then
         rm -rf -- "$tmp" "$tmp_view"
@@ -212,7 +208,9 @@ fi
 
 # Append contents of ignore file
 if [[ -f ${ignore_file=$XDG_CONFIG_HOME/aurutils/sync/ignore} ]]; then
-    while IFS="#" read -r i _; do [[ $i ]] && pkg_i+=("$i"); done < "$ignore_file"
+    while IFS='#' read -r i _; do
+        [[ $i ]] && pkg_i+=("$i")
+    done < "$ignore_file"
 fi
 
 if (( rotate )); then
@@ -257,7 +255,7 @@ fi
 if [[ -s argv ]]; then
     # shellcheck disable=SC2094
     # $1 pkgname $2 depends $3 pkgbase $4 pkgver
-    xargs --arg-file=argv aur depends --table >depends
+    xargs -a argv aur depends --table >depends
 else
     plain >&2 "there is nothing to do"
     exit
@@ -294,7 +292,7 @@ cut -f2 --complement depends | sort -u >pkginfo
 } >filter
 
 # pkgname queue (AUR + repos)
-if order depends >queue_0; then
+if cut -f1,2 depends | tr_ver | tsort >queue_0; then
     tac queue_0 | lib32 | complement filter >queue_1
 else
     # input contains a loop
@@ -321,9 +319,11 @@ fi
 # Link build files in the queue (absolute links)
 parallel -X ln -s "$(pwd -P)"/{} "$tmp_view" :::: "$tmp"/queue
 
-# Check if dependency graph is valid
 if (( graph )); then
-    aur graph "$tmp_view"/*/.SRCINFO >/dev/null
+    if ! aur graph "$tmp_view"/*/.SRCINFO >/dev/null; then
+        error '%s: failed to validate dependency graph' "$argv0"
+        exit 1
+    fi
 fi
 
 if (( view )); then
@@ -344,10 +344,10 @@ if (( view )); then
           find "$tmp_view" -maxdepth 1 -type f
 
           # Print build directories in dependency order
-          xargs -I{} -a "$tmp"/queue find -L "$tmp_view"/{} -maxdepth 1
+          xargs -a "$tmp"/queue -I{} find -L "$tmp_view"/{} -maxdepth 1
         } | viewer "$tmp_view"
     else
-        error '%s: no viewer found, please install vifm or define AUR_PAGER' "$argv0"
+        error '%s: no viewer found, please install vifm or set AUR_PAGER' "$argv0"
         exit 1
     fi
     xargs -a "$tmp/queue" aur fetch --confirm-seen
