srcver: add separator before first failed package
Otherwise it's difficult to distinguish the pkgname/pkgver output
visually from the error of the first failed package.

diff --git a/lib/aur-srcver b/lib/aur-srcver
--- a/lib/aur-srcver
+++ b/lib/aur-srcver
@@ -115,6 +115,10 @@ for d in "$tmp"/*/; do # iterate over directories
     fi
 done
 
+if (( ${#failed[@]} )); then
+    printf >&2 '8<----\n'
+fi
+
 for f in "${failed[@]}"; do
     printf >&2 '%s: makepkg %s failed for package %s\n' "$argv0" "${makepkg_args[*]}" "$f"
 
