Lib move (#290)
* allow execution of user defined scripts

AladW/aurutils#288 suggests using the "git approach" for wrapping
multiple scripts under a common command.

Provide a similar mechanism that git has for user defined sub-commands.

If a script named 'aur-myscript' is available on $PATH, it can be
invoked using:
    $ aur myscript [arguments]

* aur: list core and user made commands separately

Provide similar information like `git help -a` does to allow users
better distinguish between core and user made scripts.

diff --git a/lib/rpc-deps b/lib/rpc-deps
--- a/lib/rpc-deps
+++ b/lib/rpc-deps
@@ -1,6 +1,6 @@
 #!/bin/bash
 set -o noclobber
-readonly argv0=aurchain
+readonly argv0=rpc-deps
 readonly PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
 
 declare mode=aur
@@ -11,7 +11,7 @@ count() {
     if num=$(jq -r '.resultcount' "$1" | awk '{s += $1} END {print s}'); then
         printf '%d' "$num"
     else
-        error "$argv0: invalid argument"
+        printf '%s: invalid argument\n' "$argv0" >&2
         exit 22
     fi
 }
@@ -42,11 +42,11 @@ tabulate() {
 chain() {
     declare -i num
 
-    aursearch -ir -- "$@" > json/0 || exit
+    aur rpc -t info -- "$@" > json/0 || exit
     num=$(count json/0)
 
     if [[ $num -lt 1 ]]; then
-        error "$argv0: no packages found"
+        printf '%s: no packages found\n' "$argv0" >&2
         exit 1
     fi
 
@@ -59,11 +59,11 @@ chain() {
         cut -f1 tsv/$sub >> seen
 
         # Avoid querying duplicates (#4)
-        readarray -t target < <(cut -f2 tsv/$sub | strip_version | grep -Fxvf seen)
+        mapfile -t target < <(cut -f2 tsv/$sub | strip_version | grep -Fxvf seen)
 
         # XXX AUR does not support querying pkgver (#10)
         if [[ ${target[*]} ]]; then
-            aursearch -ir -- "${target[@]}" > json/$a || exit
+            aur rpc -t info -- "${target[@]}" > json/$a || exit
         else
             break
         fi
@@ -78,12 +78,12 @@ chain() {
     done
 
     if ((a > 30)); then
-        error "$argv0: total requests: $((++a)) (out of range)"
+        printf '%s: total requests: %d (out of range)\n' "$argv0" $((++a)) >&2
         exit 34
     fi
 
     if ! cut -f1,2 tsv/n | strip_version | tsort; then
-        error "$argv0: invalid argument"
+        printf '%s: invalid argument\n' "$argv0" >&2
         exit 22
     fi
  
@@ -97,17 +97,11 @@ trap_exit() {
 }
 
 usage() {
-    plain "usage: $argv0 [-at] pkgname..."
+    printf 'usage: %s [-at] pkgname...\n' "$argv0" >&2
     exit 1
 }
 
 readonly -f count tabulate chain trap_exit usage
-
-source /usr/share/makepkg/util.sh || exit
-
-if [[ -t 2 && ! -o xtrace ]]; then
-    colorize
-fi
 
 while getopts :at OPT; do
     case $OPT in
