actions: run shellcheck
If a step from a job fails the remaining steps are cancelled.
But we are interested in the results from shellcheck, even when the
option parsing consistency test fails.

For that, we include the condition: `if: success() || failure()` which
ensures the step will run even when the job status is already failure.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -5,6 +5,12 @@ jobs:
     runs-on: ubuntu-latest
     container: archlinux/base
     steps:
-      - run: pacman -Syu --noconfirm base base-devel
+      - run: pacman -Syu --noconfirm base base-devel shellcheck
       - uses: actions/checkout@v2
-      - run: test/parseopt-consistency
+
+      - name: Option parsing consistency
+        run: test/parseopt-consistency
+
+      - name: Shellcheck
+        if: success() || failure() # Do not fail-fast
+        run: make shellcheck
